class Category {
  String? categoryId;
  String? categoryName;
  String? categorySlug;
  List<String>? productIds;

  Category({
    this.categoryId, this.categoryName, this.categorySlug, this.productIds
  });

  Autogenerated.fromJson(Map<String, dynamic> json) {
    productIds = json['products'].cast<String>();
    categoryId = json['_id'];
    categoryName = json['name'];
    categorySlug = json['slug'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['products'] = this.productIds;
    data['_id'] = this.categoryId;
    data['name'] = this.categoryName;
    data['slug'] = this.categorySlug;
    return data;
  }
}